### PR TITLE
fixed entered and left chat event

### PR DESCRIPTION
**Pull request by ZEREX222**
image

need to process entering and leaving action in the code

### CODE REVIEW

**Comment by Drednote** [comment]
Hi! This is my mistake; I accidentally overlooked this type of update :( However, I wouldn't want to add any custom logic to AbstractUpdateRequest, so could you please remove the definition of whether the bot has been added or removed from the chat and just leave the status update? It should be done similarly to CHAT_MEMBER_UPDATED . And could you move the if-else statement to CHAT_MEMBER_UPDATED to maintain the same order as the properties in Update? 

Thank you for using and making changes to this library!

**Comment by ZEREX222** [comment]
> Hi! This is my mistake; I accidentally overlooked this type of update :( However, I wouldn't want to add any custom logic to AbstractUpdateRequest, so could you please remove the definition of whether the bot has been added or removed from the chat and just leave the status update? It should be done similarly to CHAT_MEMBER_UPDATED . And could you move the if-else statement to CHAT_MEMBER_UPDATED to maintain the same order as the properties in Update?
> 
> Thank you for using and making changes to this library!

did it.. better? :) update.getMyChatMember() doesn't have a user inside.

**Comment by Drednote** [comment]
create new RequestType MY_CHAT_MEMBER_UPDATED and move this statement to else if (update.getChatMember() != null) { statement

**Comment by ZEREX222** [comment]
> > did it.. better? :) update.getMyChatMember() doesn't have a user inside.
> 
> Yes, but create new RequestType MY_CHAT_MEMBER_UPDATED and move this statement to else if (update.getChatMember() != null) { statement

did it. check please.

**Comment by Drednote** [comment]
why you dont parse user? i see user presents on your screenshot.

**Comment by ZEREX222** [comment]
> Wait. But as far as I understand, it is not the bot itself that performs the action, but the one who excludes or adds it. And this user is in from. Isn't that right? So you just need to put the value from from into user.

sorry.. you are right.. just for the first time see this lib :) fixed it

**Review by Drednote — APPROVED** [review]

**Pull request merged**
